### ISSUE TITLE
Airdrop - JSON-RPC error: "Internal error"

### ISSUE THREAD

**Issue by ilencio** [darkrenaissance/darkfi#138]
I can't airdrop

```
~/darkfi$ ./drk airdrop 42.69 DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq
Error: Failed to request airdrop

Caused by:
    JSON-RPC error: "Internal error"
 
```

```
~/darkfi$ ./drk airdrop 13.37 BobvfQrDaf32VNhVtX6Adyi3WGfPpPYZPJBn6rnrxHKm
Error: Failed to request airdrop

Caused by:
    JSON-RPC error: "Internal error" 
```

rustc 1.67.0 (fc594f156 2023-01-24)

**Comment by aggstam** [comment]
Faucet instance is down as we perform our first findings fixes.
Once finished we tag the hotfix version and reset the network.
We will update the ticket when its done to let you know.

**Comment by aggstam** [comment]
Network have been reset!
Please stop darkfid process, pull and recompile from master, then remove your local database folder(located at ~/.config/darkfi/blockchain) and start darkfid.
After syncing perform a `./drk scan --reset` so your wallet is synced to chain!
Let us know if issue persists, otherwise we can close this ticket.

**Comment by ilencio** [comment]
Ok, it works now. You can close the ticket, thank you for the support!:)
