### ISSUE TITLE
payment transfer issue

### ISSUE THREAD

**Issue by lakshmanpython** [darkrenaissance/darkfi#156]
Hi 

unable to perform payment transfer...
~/darkfi# ./drk wallet --coins
Fetching OwnCoins from the wallet
Fetching Aliases from the wallet
 Coin                                         | Spent | Token ID                                     | Aliases | Value             | Spend Hook | User Data 
----------------------------------------------+-------+----------------------------------------------+---------+-------------------+------------+-----------
 FRtwaj5k4M8JTfQ3Vp5V8tAgK7Jg9g3qg6sdZBJyHPgK | true  | 12ea8e3KVuBhmSnr29iV34Zd2RsD1MEeGk9xJhcipUqx | DARK    | 10000000000 (100) | -          | - 

root@vm:~/darkfi# ./drk transfer 10 DARK 8sRwB7AwBTKEkyTW6oMyRoJWZhJwtqGTf7nyHwuJ74pj > pay.txt
Fetching Aliases from the wallet
Fetching OwnCoins
Fetching OwnCoins from the wallet
Error: Failed to create payment transaction

Caused by:
    **Did not find any coins with token ID: 12ea8e3KVuBhmSnr29iV34Zd2RsD1MEeGk9xJhcipUqx**

#have a coins but it saying no coins.

**Comment by aggstam** [comment]
Hello,
Based on the output the coin you have in your wallet is mark as spent, therefore the behavior(no finding any coins) is correct.
You can unspend the coin with `./drk unspend <COIN>`, where COIN in your case would be: _FRtwaj5k4M8JTfQ3Vp5V8tAgK7Jg9g3qg6sdZBJyHPgK_
It might be better to reset your wallet using `./drk scan --reset`.
Also verify that your node is in correct block height, since we made a reset last week you might not have cleaned up the old blockchain.
Current slot number at time of writting this is 6372.

**Comment by lakshmanpython** [comment]
Yes now can able to do
