### ISSUE TITLE
Not working on RISCV boards such as VisionFiveV2 because of ring dependency set low on some package

### ISSUE THREAD

**Issue by sdanfa** [darkrenaissance/darkfi#228]
Hello,

One of the packges that are pulled when doing make ircd, it fails with ring package error since it's trying to use V0.16.x instead of V.0.17.X. Can you please fix this somehow? I would like to run ircd on riscv architecture. Everything else builds fine but fails at this.

Thanks!

**Comment by aggstam** [comment]
Hello,

You may use this [docker](https://github.com/darkrenaissance/darkfi/blob/master/contrib/docker/riscv.Dockerfile) build file for reference, on how to build ircd for RISC-V.
If you are developing on a native RISC-V environment, you will find every step needed, like compiling sqlite and linking it to rust compile, to properly build for it.
We have already ported/patched ring(and rest needed deps) to work for RISC-V, so you can simply import them in the bottom of Cargo.toml, like [here](https://github.com/darkrenaissance/darkfi/blob/master/contrib/docker/riscv.Dockerfile#L51-L56).
If you want to use this builder file for ircd:
1. Copy it into tag v0.4.1(since it only exists on master)
2. Add this extra line [here](https://github.com/darkrenaissance/darkfi/blob/master/contrib/docker/riscv.Dockerfile#L62C5-L62C63): `(if [ -e ircd ]; then cp -a ircd compiled-bins/; fi;) && \`
3. Execute: `docker build . --pull --no-cache --shm-size=196m -t darkfi:riscv -f ./contrib/docker/riscv.Dockerfile -o riscv-bins --build-arg BINS=ircd`

Builded binary will work without issues, as I constantly test it on a RISC-V board.
Let me know if you require extra help and/or information!

KR
