### ISSUE TITLE
question on make and rust workspace build process

### ISSUE THREAD

**Issue by pipelight** [darkrenaissance/darkfi#243]
It is easy to install the many darkfi binaries thanks to the make scripts.
But I was wondering why you chose not to use the [[bin]] attribute to build them automatically with
a `cargo build` on fresh install on the workspace root.

Am I missing something ? Like a developer guide ?
Should I seek help and speak with maintainers where you know ?

**Comment by aggstam** [comment]
Hey @pipelight ,

Makefiles are way superior and more flexible than any other building method known to mankind.
Additionally, they are lang agnostic so you can manage everything in your project when parts use dirrefent languages and/or targets. As far as I know, cargo doesn't provide any of this functionality(like a pure scripting) therefore we shouldn't use it as a root builder.

Happy to hear your thoughts/counterpoints on irc, since this is more of a conversation question rather than an issue.

**Comment by parazyd** [comment]
![skill](https://github.com/darkrenaissance/darkfi/assets/9220323/c85ee855-e5a7-4d37-8533-975986089d4b)
